### ISSUE TITLE
Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by arturoherrero** [gperfutils/gbench#10]
I'm trying to execute a basic example but I'm getting an exception.

```
@Grab(group='org.gperfutils', module='gbench', version='0.4.2-groovy-2.3')
import groovyx.gbench.*

def r = benchmark {
    'Parallel Assignment' {
        def (a, b, c, d, e, f, g, h) = [1, 2, 3, 4, 5, 6, 7, 8]
    }
    'Sequential Assignment' {
        def a = 1
        def b = 2
        def c = 3
        def d = 4
        def e = 5
        def f = 6
        def g = 7
        def h = 8
    }
}
r.prettyPrint() 
 
Environment
===========
* Groovy: 2.3.8
* JVM: Java HotSpot(TM) 64-Bit Server VM (24.71-b01, Oracle Corporation)
    * JRE: 1.7.0_71
    * Total Memory: 156 MB
    * Maximum Memory: 1820.5 MB
* OS: Mac OS X (10.10.1, x86_64)

Options
=======
* Warm Up: Auto (- 60 sec)
* CPU Time Measurement: On

Exception thrown

java.lang.NoClassDefFoundError: java/util/function/Consumer
	at groovyx.gbench.BenchmarkBuilder.doRun(BenchmarkBuilder.groovy:87)
	at groovyx.gbench.BenchmarkBuilder.this$2$doRun(BenchmarkBuilder.groovy)
	at groovyx.gbench.BenchmarkBuilder$this$2$doRun$1.callCurrent(Unknown Source)
	at groovyx.gbench.BenchmarkBuilder.run(BenchmarkBuilder.groovy:83)
	at groovyx.gbench.BenchmarkBuilder$run.call(Unknown Source)
	at groovyx.gbench.BenchmarkStaticExtension.benchmark(BenchmarkStaticExtension.groovy:33)
	at groovyx.gbench.BenchmarkStaticExtension.benchmark(BenchmarkStaticExtension.groovy)
	at ConsoleScript0.run(ConsoleScript0:4)
Caused by: java.lang.ClassNotFoundException: java.util.function.Consumer
	... 8 more
```

In the other hand, I try with the Benchmark annotation transformation and works fine!
```
@Grab(group='org.gperfutils', module='gbench', version='0.4.2-groovy-2.3')
import groovyx.gbench.*

@groovyx.gbench.Benchmark
void 'Parallel Assignment'() {
    def (a, b, c, d, e, f, g, h) = [1, 2, 3, 4, 5, 6, 7, 8]
}

@groovyx.gbench.Benchmark
void 'Sequential Assignment'() {
    def a = 1
    def b = 2
    def c = 3
    def d = 4
    def e = 5
    def f = 6
    def g = 7
    def h = 8
}

'Parallel Assignment'()
'Sequential Assignment'()

benchmark  void Parallel Assignment()  user:141000 system:6000 cpu:147000 real:163000
benchmark  void Sequential Assignment()  user:1000 system:4000 cpu:5000 real:26000
```

**Comment by masatonagai** [comment]
Thanks for the report. Could you grab ver 0.4.2-groovy-2.2 instead until this problem is resolved. The version should work.

**Comment by masatonagai** [comment]
I fixed it and uploaded jar to Maven Central repository.

**Comment by smartdreamer** [comment]
I tested taday and I get the same exception trace as @arturoherrero (
java.lang.NoClassDefFoundError: java/util/function/Consumer). BTW, 0.4.2-groovy-2.2 has the same problem.

The problem is that BenchmarkBuilder relies on Consumer interface. I'm running on JDK 7, but the Consumer interface was introduced in JDK 8. Running on JDK 8 works.

So the issue is still here for non-jdk-8 users.

**Comment by masatonagai** [comment]
I'll re-test this issue.

**Comment by arturoherrero** [comment]
Can you update the README because it's a little bit outdated we have Groovy 2.4 as the latest version. 
```
@Grab('org.gperfutils:gbench:0.4.2-groovy-2.1') // v0.4.2 for Groovy 2.1
```
Thank you!

**Comment by masatonagai** [comment]
@smartdreamer 
Can you paste Created-by in MANIFEST.MF of  $HOME/.groovy/grapes/org.gperfutils/gbench/jars/gbench-0.4.2-groovy-2.2.jar?
by, for example,
```
unzip -p ~/.groovy/grapes/org.gperfutils/gbench/jars/gbench-0.4.2-groovy-2.2.jar META-INF/MANIFEST.MF | grep Created-By
```
My result with re-grabbed gbench-0.4.2-groovy-2.[2|3].jar from maven repository is:
```
Created-By: 1.7.0_17-b02 (Oracle Corporation)
```
and it works with JDK 1.7.

@arturoherrero 
You're right. I'll update README in the next release :)

**Comment by arturoherrero** [comment]
I think that we could use [Travis CI][1], with a continuous integration server, we don't need to discuss about it's working in my machine.

[1]: https://travis-ci.org/

**Comment by masatonagai** [comment]
@arturoherrero 
No, we don't need to discuss about that and I just tried to say the binary on the Maven repository was built with JDK 7. 

I tested gbench with JDK 7 on Travis CI server and the tests passed.
https://travis-ci.org/gperfutils/gbench/builds/48977404

But I don't know the difference between 'it works in my machine' and 'it works in Travis CI machine' as an answer for 'it does not work in my machine'.

**Comment by arturoherrero** [comment]
I just tried to open more options to have gbench working for everybody. But, maybe the problem is not testing the code is the jar file in Maven repositories. I don't know exactly why there are people that has this working and other that not.

**Comment by masatonagai** [comment]
@arturoherrero 
Thank you, I understand. Yes, the test is necessary.

**Comment by smartdreamer** [comment]
@masatonagai Here's what I get testing today from the MANIFEST:
gbench-0.4.2-groovy-2.**2**.jar: Created-By: **1.7.0_17-b02** (Oracle Corporation)
gbench-0.4.2-groovy-2.**3**.jar: Created-By: **1.8.0_11-b12** (Oracle Corporation)

**Comment by masatonagai** [comment]
@smartdreamer 
Thank you. So gbench-0.4.2-groovy-2.2 should work. gbench-0.4.2-groovy-2.3 will work after clearing the cache and re-Grab it.

I'll release v0.4.3 soon for resolving this issue and some.
